### ISSUE TITLE
Why dependency on privoxy?

### ISSUE THREAD

**Issue by jhoogeboom** [adibalcan/PyTor#1]
Why does it rely on Privoxy? With SocksiPy and urllib should be all set right? 
Like in: https://stem.torproject.org/tutorials/to_russia_with_love.html

**Comment by adibalcan** [comment]
1. With Privoxy I can detect when changing isn't ready by getting a Privoxy intermediate source page.
2. If you use this, all of your http requests will use tor.

**Comment by adibalcan** [comment]
If you can please improve this.

**Comment by jhoogeboom** [comment]
I'm just learning python, so it was more out of interest and curiosity than a sense that I know how to do it better :)
1. the change of the id/ip ? the stem.controller contains msg.handler that should be able to tell you when the new id/ip has been established, I think?

I didn't know requests before, but now I see it, it only does HTTP, hence the reason you need a bridge between the HTTP and the sockets (privoxy). I stumbled on something else though, requesocks, request forked to work with socks proxies: https://github.com/dvska/requesocks. Might be interesting.
