### ISSUE TITLE
What is purpose of pytor.password

### ISSUE THREAD

**Issue by kc1** [adibalcan/PyTor#3]
Is this to get the password from the torrc file or to set the password?

**Comment by adibalcan** [comment]
the next command is for generate torrc password **tor --hash-password YOURPASSWORD** and this **pytor.password** is password for connection at torrc

**Comment by kc1** [comment]
Adrian, I have set the project up and have it working, without pytor.password='YOURPASSWORD' . I still don't understand how you use this, since you don't need to set it to have the script working. Could you give an example please? I would like to use it for authentication puposes.
